### ISSUE TITLE
Getting failed to download [reopened]

### ISSUE THREAD

**Issue by anilravat** [lachiejames/npm-downloads-increaser#102]
Getting this error.
![image](https://github.com/lachiejames/npm-downloads-increaser/assets/42377280/40ee29ab-4ad8-420e-bb54-0cda12be36e4)

But the package is active: https://www.npmjs.com/package/@azahinhasan/age-calculator

**Comment by lachiejames** [comment]
Hey @hryhorii515, it looks like the [@azahinhasan/age-calculator](https://www.npmjs.com/package/@azahinhasan/age-calculator) npm package was never indexed on https://npms.io/, which `npm-downloads-increaser` depends on.  This is surprising since new npm packages typically get indexed on there in less than 24hrs.

I suspect that npms refused to index this package due to insufficient details in the `package.json`, such as the empty `description` field.

https://github.com/azahinhasan/age_calculator_npm_package/blob/e37fd550d39071bcd6f2ee9d4040a430fd983167/package.json

If you have access to this repo, try the following:
- Populate the description
- Republish the package to npm
- Wait for npms.io to index the package then try again

**Comment by hryhorii515** [comment]
Thanks @lachiejames
